Repository ssc-dsai/canchat-v2, pull requests merged in 2025-07, with the labels that each got.

#151 fix(config): update environment variable for bypassing web search embedding and retrieval
  backend/open_webui/config.py
Labels: bug

#152 fix(metrics): Enhance model metrics access and display for analysts
  backend/open_webui/routers/metrics.py
  backend/open_webui/routers/models.py
  src/lib/components/workspace/Metrics.svelte
  src/lib/i18n/locales/en-GB/translation.json
  src/lib/i18n/locales/fr-CA/translation.json
  src/routes/(app)/workspace/+layout.svelte
  src/routes/(app)/workspace/metrics/+page.svelte
Labels: bug

#154 docs - Chat 738 - Revise branding
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  INSTALLATION.md
  README.md
  SECURITY.md
  TROUBLESHOOTING.md
  backend/open_webui/config.py
  docs/CONTRIBUTING.md
  hatch_build.py
  static/opensearch.xml
Labels: documentation

#153 feat(leaderboard): implement hybrid ELO rating system with enhanced feedback processing
  src/lib/components/admin/Evaluations.svelte
  src/lib/components/admin/Evaluations/Feedbacks.svelte
  src/lib/components/admin/Evaluations/Leaderboard.svelte
  src/lib/i18n/locales/en-GB/translation.json
  src/lib/i18n/locales/fr-CA/translation.json
  src/routes/(app)/admin/+layout.svelte
Labels: bug, enhancement

#159 feat(mcp): add new dependencies for fastmcp, pytz, crewai, and azure-storage-blob to toml file
  pyproject.toml
Labels: enhancement

#162 feat(help): add issue reporting and suggestion modals with corresponding icons
  src/lib/components/chat/MessageInput/InputMenu.svelte
  src/lib/components/chat/Messages/ResponseMessage.svelte
Labels: enhancement

#158 feat(ci/security): add a scan by trivy to create security report.
  .github/workflows/security-scan-trivy.yaml
Labels: enhancement

#161 fix(socket): improve error handling in Redis lock management and cleanup task
  backend/crew_mcp_integration.py
  backend/open_webui/main.py
  backend/open_webui/socket/main.py
  backend/open_webui/socket/utils.py
Labels: bug, enhancement

#172 fix(PromptEditor): update access control initialization for non-admin users to ensure prompts are private by default
  src/lib/components/workspace/Prompts/PromptEditor.svelte
  src/lib/components/workspace/common/AccessControl.svelte
Labels: bug

#175 fix(healthcheck): improve database health check with timeout and error handling
  backend/open_webui/main.py
Labels: bug

#170 feat(prompts): add pagination to prompt list for improved navigation
  backend/open_webui/models/feedbacks.py
  backend/open_webui/models/prompts.py
  backend/open_webui/routers/evaluations.py
  backend/open_webui/routers/prompts.py
  src/lib/apis/evaluations/index.ts
  src/lib/apis/prompts/index.ts
  src/lib/components/admin/Evaluations.svelte
  src/lib/components/admin/Evaluations/Feedbacks.svelte
  src/lib/components/workspace/Prompts.svelte
  src/routes/(app)/+layout.svelte
Labels: enhancement

#176 feat(migration/prompts/feedbacks): performance indexes and optimize pagination system
  backend/open_webui/migrations/versions/5251af02c082_add_prompt_performance_indexes.py
  backend/open_webui/migrations/versions/ed37e461f285_add_feedback_performance_indexes.py
  src/lib/components/chat/MessageInput/Commands.svelte
  src/lib/components/chat/MessageInput/Commands/Prompts.svelte
  src/lib/i18n/locales/en-GB/translation.json
  src/lib/i18n/locales/fr-CA/translation.json
Labels: enhancement

#183 feat(qdrant): Add comprehensive cleanup scripts for Qdrant vector database
  .env.example
  backend/open_webui/config.py
  backend/open_webui/constants.py
  backend/open_webui/retrieval/reindex_utils.py
  backend/open_webui/retrieval/utils.py
  backend/open_webui/retrieval/vector/dbs/qdrant.py
  backend/open_webui/routers/chats.py
  backend/open_webui/routers/files.py
  backend/open_webui/routers/knowledge.py
  backend/open_webui/routers/retrieval.py
  backend/scripts/fast_cronjob_simulator.py
  backend/scripts/k8s_vector_cleanup.py
Labels: bug, enhancement
