Repository ssc-dsai/canchat-v2, pull requests merged in 2025-08, with the labels that each got.

#190 fix(prompts): issue where public prompts were not being seen by user
  backend/open_webui/models/prompts.py
  backend/open_webui/routers/prompts.py
Labels: bug

#191 feat(prompts): optimize prompt retrieval with access control and public prompts
  backend/open_webui/models/prompts.py
  backend/open_webui/routers/prompts.py
Labels: bug

#192 fix(prompts): update access control logic for public and private prompts
  backend/open_webui/models/prompts.py
  backend/open_webui/routers/prompts.py
  src/lib/components/workspace/Prompts.svelte
Labels: bug

#194 fix(prompts): fixed prompt query logic for sqlite and posgresql
  backend/open_webui/models/prompts.py
  backend/open_webui/routers/prompts.py
Labels: bug

#202 fix(retrieval): add missing dependency. chat-879
  CHANGELOG.md
  backend/open_webui/routers/retrieval.py
  package-lock.json
  package.json
Labels: bug

#203 feat(docker): optimize disk usage during builds and cleanup processes
  .github/workflows/docker-build.yaml
  Dockerfile
Labels: bug, Priority

#204 feat(docker): enhance cleanup processes in Docker build to optimize disk usage
  .github/workflows/docker-build.yaml
  Dockerfile
Labels: bug, Priority

#206 fix(docker): update permissions handling to skip multiple large static asset directories for improved space management
  Dockerfile
Labels: bug, Priority

#212 fix(docker): optimize Dockerfile for reduced image size and improved build efficiency
  .github/workflows/docker-build.yaml
  Dockerfile
Labels: bug, Priority

#214 fix(docker-build): disable cache-to option to avoid disk space issues
  .github/workflows/docker-build.yaml
Labels: Priority

#201 feat(user): add role update functionality in EditUserModal
  src/lib/components/admin/Users/UserList/EditUserModal.svelte
Labels: bug

#208 fix(chat): clear sessionStorage for default models on new chats
  src/lib/components/chat/Chat.svelte
Labels: bug
